In [2]:
import tensorflow as tf
import numpy as np
mnist = tf.keras.datasets.mnist

def test_model(model: tf.keras.models.Sequential):
    (x_train, y_train), (x_test, y_test) = mnist.load_data()
    x_train, x_test = x_train / 255.0, x_test / 255.0
    x = np.concatenate((x_train, x_test))
    y = np.concatenate((y_train, y_test))
    splitted_x = np.array_split(x, 4)
    splitted_y = np.array_split(y, 4)
    x_train = np.concatenate(
        (np.concatenate((splitted_x[0], splitted_x[1])), splitted_x[2]))
    y_train = np.concatenate(
        (np.concatenate((splitted_y[0], splitted_y[1])), splitted_y[2]))
    x_test = splitted_x[3]
    y_test = splitted_y[3]
    loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
    model.compile(
        optimizer='adam',
        loss=loss_fn,
        metrics=['accuracy']
    )
    model.fit(x_train, y_train, epochs=5)
    model.evaluate(x_test,  y_test, verbose=2)
    probability_model = tf.keras.Sequential([
        model,
        tf.keras.layers.Softmax()
    ])
    print(f"{y_test[:1] = }")
    print(f"{probability_model(x_test[:1]) = }")

## Ohne Hidden Layer

In [ ]:
test_model(
    tf.keras.models.Sequential([
        tf.keras.layers.Flatten(input_shape=(28, 28)),
        tf.keras.layers.Dropout(0.2),
        tf.keras.layers.Dense(10)
    ])
)

Epoch 1/5
1641/1641 [==============================] - 5s 3ms/step - loss: 0.5385 - accuracy: 0.8544
Epoch 2/5
1641/1641 [==============================] - 6s 3ms/step - loss: 0.3516 - accuracy: 0.8984
Epoch 3/5
1641/1641 [==============================] - 5s 3ms/step - loss: 0.3324 - accuracy: 0.9048
Epoch 4/5
1641/1641 [==============================] - 4s 3ms/step - loss: 0.3244 - accuracy: 0.9077
Epoch 5/5
1641/1641 [==============================] - 4s 2ms/step - loss: 0.3191 - accuracy: 0.9091
547/547 - 1s - loss: 0.2624 - accuracy: 0.9271 - 664ms/epoch - 1ms/step
y_test[:1] = array([9], dtype=uint8)
probability_model(x_test[:1]) = <tf.Tensor: shape=(1, 10), dtype=float32, numpy=
array([[2.9867397e-10, 1.7557418e-06, 1.3932994e-05, 3.7362322e-04,
        1.0486235e-02, 2.2105378e-05, 1.4454747e-07, 6.8720680e-04,
        2.0854296e-03, 9.8632962e-01]], dtype=float32)>


## 2 Hidden Layer, eines mit mindestens 16 Neuronen

In [5]:
test_model(
    tf.keras.models.Sequential([
        tf.keras.layers.Flatten(input_shape=(28, 28)),
        tf.keras.layers.Dense(200, activation='relu'),
        tf.keras.layers.Dense(20),
        tf.keras.layers.Dropout(0.2),
        tf.keras.layers.Dense(10)
    ])
)

Epoch 1/5
1641/1641 [==============================] - 6s 3ms/step - loss: 0.2984 - accuracy: 0.9129
Epoch 2/5
1641/1641 [==============================] - 5s 3ms/step - loss: 0.1303 - accuracy: 0.9613
Epoch 3/5
1641/1641 [==============================] - 5s 3ms/step - loss: 0.0892 - accuracy: 0.9726
Epoch 4/5
1641/1641 [==============================] - 5s 3ms/step - loss: 0.0686 - accuracy: 0.9792
Epoch 5/5
1641/1641 [==============================] - 5s 3ms/step - loss: 0.0533 - accuracy: 0.9829
547/547 - 1s - loss: 0.0761 - accuracy: 0.9787 - 855ms/epoch - 2ms/step
y_test[:1] = array([9], dtype=uint8)
probability_model(x_test[:1]) = <tf.Tensor: shape=(1, 10), dtype=float32, numpy=
array([[2.2439860e-08, 1.0607018e-08, 3.7767761e-11, 1.4254492e-06,
        6.6828710e-05, 2.6934458e-08, 1.2971172e-09, 2.6582597e-07,
        3.2532023e-07, 9.9993110e-01]], dtype=float32)>


## NN2 mit hard_sigmoid als Aktivierungsfunktion

In [6]:
test_model(
    tf.keras.models.Sequential([
        tf.keras.layers.Flatten(input_shape=(28, 28)),
        tf.keras.layers.Dense(200, activation='hard_sigmoid'),
        tf.keras.layers.Dense(20),
        tf.keras.layers.Dropout(0.2),
        tf.keras.layers.Dense(10)
    ])
)

Epoch 1/5
1641/1641 [==============================] - 6s 3ms/step - loss: 0.4623 - accuracy: 0.8643
Epoch 2/5
1641/1641 [==============================] - 6s 4ms/step - loss: 0.2319 - accuracy: 0.9327
Epoch 3/5
1641/1641 [==============================] - 6s 4ms/step - loss: 0.1579 - accuracy: 0.9530
Epoch 4/5
1641/1641 [==============================] - 6s 4ms/step - loss: 0.1152 - accuracy: 0.9653
Epoch 5/5
1641/1641 [==============================] - 6s 4ms/step - loss: 0.0891 - accuracy: 0.9734
547/547 - 1s - loss: 0.0852 - accuracy: 0.9745 - 1s/epoch - 2ms/step
y_test[:1] = array([9], dtype=uint8)
probability_model(x_test[:1]) = <tf.Tensor: shape=(1, 10), dtype=float32, numpy=
array([[3.74268893e-07, 9.01700389e-07, 2.79416188e-08, 1.05859115e-04,
        1.80422925e-04, 5.93603227e-06, 1.85940774e-08, 4.76712776e-05,
        4.40474105e-05, 9.99614716e-01]], dtype=float32)>


## NN2 mit linear als Aktivierungsfunktion

In [7]:
test_model(
    tf.keras.models.Sequential([
        tf.keras.layers.Flatten(input_shape=(28, 28)),
        tf.keras.layers.Dense(200, activation='linear'),
        tf.keras.layers.Dense(20),
        tf.keras.layers.Dropout(0.2),
        tf.keras.layers.Dense(10)
    ])
)

Epoch 1/5
1641/1641 [==============================] - 6s 3ms/step - loss: 0.4787 - accuracy: 0.8588
Epoch 2/5
1641/1641 [==============================] - 5s 3ms/step - loss: 0.3898 - accuracy: 0.8889
Epoch 3/5
1641/1641 [==============================] - 5s 3ms/step - loss: 0.3714 - accuracy: 0.8951
Epoch 4/5
1641/1641 [==============================] - 5s 3ms/step - loss: 0.3588 - accuracy: 0.8990
Epoch 5/5
1641/1641 [==============================] - 5s 3ms/step - loss: 0.3531 - accuracy: 0.9006
547/547 - 1s - loss: 0.2861 - accuracy: 0.9152 - 1s/epoch - 2ms/step
y_test[:1] = array([9], dtype=uint8)
probability_model(x_test[:1]) = <tf.Tensor: shape=(1, 10), dtype=float32, numpy=
array([[9.7149483e-11, 6.5002024e-07, 2.2907993e-07, 6.4493594e-05,
        4.0349173e-03, 3.6621327e-07, 3.8920080e-09, 1.0599407e-03,
        1.3806188e-04, 9.9470139e-01]], dtype=float32)>


## 8 Hidden Layer, eines mit maximal 4 Neuronen

In [8]:
test_model(
    tf.keras.models.Sequential([
        tf.keras.layers.Flatten(input_shape=(28, 28)),
        tf.keras.layers.Dense(10, activation='relu'),
        tf.keras.layers.Dense(10),
        tf.keras.layers.Dense(10),
        tf.keras.layers.Dense(10),
        tf.keras.layers.Dense(10),
        tf.keras.layers.Dense(10),
        tf.keras.layers.Dense(10),
        tf.keras.layers.Dense(4),
        tf.keras.layers.Dropout(0.2),
        tf.keras.layers.Dense(10)
    ])
)

Epoch 1/5
1641/1641 [==============================] - 6s 3ms/step - loss: 0.9260 - accuracy: 0.6777
Epoch 2/5
1641/1641 [==============================] - 4s 3ms/step - loss: 0.6826 - accuracy: 0.7782
Epoch 3/5
1641/1641 [==============================] - 4s 3ms/step - loss: 0.6255 - accuracy: 0.8042
Epoch 4/5
1641/1641 [==============================] - 4s 3ms/step - loss: 0.6001 - accuracy: 0.8144
Epoch 5/5
1641/1641 [==============================] - 5s 3ms/step - loss: 0.5793 - accuracy: 0.8288
547/547 - 1s - loss: 0.3790 - accuracy: 0.9087 - 902ms/epoch - 2ms/step
y_test[:1] = array([9], dtype=uint8)
probability_model(x_test[:1]) = <tf.Tensor: shape=(1, 10), dtype=float32, numpy=
array([[1.1661984e-04, 6.1540959e-07, 3.1813148e-03, 1.7870823e-04,
        7.2118910e-03, 3.3884137e-07, 5.8275116e-08, 1.8940130e-02,
        5.1891648e-06, 9.7036517e-01]], dtype=float32)>


## Tutorial Model mit 0.2 Dropout

In [9]:
test_model(
    tf.keras.models.Sequential([
        tf.keras.layers.Flatten(input_shape=(28, 28)),
        tf.keras.layers.Dense(128, activation='relu'),
        tf.keras.layers.Dropout(0.2),
        tf.keras.layers.Dense(10)
    ])
)

Epoch 1/5
1641/1641 [==============================] - 5s 3ms/step - loss: 0.3103 - accuracy: 0.9094
Epoch 2/5
1641/1641 [==============================] - 4s 3ms/step - loss: 0.1536 - accuracy: 0.9547
Epoch 3/5
1641/1641 [==============================] - 5s 3ms/step - loss: 0.1161 - accuracy: 0.9643
Epoch 4/5
1641/1641 [==============================] - 5s 3ms/step - loss: 0.0961 - accuracy: 0.9709
Epoch 5/5
1641/1641 [==============================] - 5s 3ms/step - loss: 0.0799 - accuracy: 0.9759
547/547 - 1s - loss: 0.0761 - accuracy: 0.9769 - 810ms/epoch - 1ms/step
y_test[:1] = array([9], dtype=uint8)
probability_model(x_test[:1]) = <tf.Tensor: shape=(1, 10), dtype=float32, numpy=
array([[8.90081875e-09, 1.74918846e-09, 7.16342925e-07, 2.01208226e-04,
        1.16938550e-03, 1.59325828e-06, 5.06483614e-12, 9.81576159e-05,
        1.20157565e-04, 9.98408735e-01]], dtype=float32)>


## Tutorial Model mit 0.8 Dropout

In [10]:
test_model(
    tf.keras.models.Sequential([
        tf.keras.layers.Flatten(input_shape=(28, 28)),
        tf.keras.layers.Dense(128, activation='relu'),
        tf.keras.layers.Dropout(0.8),
        tf.keras.layers.Dense(10)
    ])
)

Epoch 1/5
1641/1641 [==============================] - 5s 3ms/step - loss: 0.7567 - accuracy: 0.7566
Epoch 2/5
1641/1641 [==============================] - 4s 3ms/step - loss: 0.5179 - accuracy: 0.8359
Epoch 3/5
1641/1641 [==============================] - 4s 2ms/step - loss: 0.4689 - accuracy: 0.8529
Epoch 4/5
1641/1641 [==============================] - 4s 3ms/step - loss: 0.4435 - accuracy: 0.8603
Epoch 5/5
1641/1641 [==============================] - 5s 3ms/step - loss: 0.4210 - accuracy: 0.8692
547/547 - 1s - loss: 0.1616 - accuracy: 0.9542 - 836ms/epoch - 2ms/step
y_test[:1] = array([9], dtype=uint8)
probability_model(x_test[:1]) = <tf.Tensor: shape=(1, 10), dtype=float32, numpy=
array([[8.2539059e-13, 3.3390362e-09, 2.0017363e-07, 9.6484160e-05,
        9.6421754e-03, 1.3806846e-06, 4.1119690e-12, 5.9175084e-04,
        3.4605198e-06, 9.8966461e-01]], dtype=float32)>
